# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-04 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_author_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='athuor',
            field=models.CharField(default='alex', max_length=32),
            preserve_default=False,
        ),
    ]
