# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-04 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_book_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
        migrations.AddField(
            model_name='book',
            name='publish_i',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publish_id', to='app01.publish'),
            preserve_default=False,
        ),
    ]
