# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-04 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authordetail',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='publish',
            options={},
        ),
        migrations.RemoveField(
            model_name='publish',
            name='address',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='country',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='website',
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='app01.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.publish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='publish',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='publish',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='AuthorDetail',
        ),
    ]
